# Document:
# http://simiki.org/docs/configuration.html
url: https://zhang787jun.github.io/Wiki
title: Jun's personal knowledge wiki
keywords: Technology, MachineLearning, DataMining, Wiki
description: A wiki website
author: zhang787jun
root: /Wiki
theme: simple
debug: True
destination: output
source: content
attach: attach
default_ext: md
pygments: true
# theme add MathJax.js
